# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]
        dotnet-version: [ '8.0.x', '9.0.x' ]
    name: ${{ matrix.os }} with .NET ${{ matrix.dotnet-version }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    # ubuntu-latest (currently 24.04) has a problem where .NET 9.0 is not available from its default APT repository
    # the current workaround is to find another .NET provider
    - name: Add additional Ubuntu APT repository
      run: sudo add-apt-repository ppa:dotnet/backports
    - name: Refresh APT repository
      run: sudo apt update
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test with .NET ${{ matrix.dotnet-version }}
      run: dotnet test -c Release --no-build
